### ISSUE TITLE
Allow more than 4 lines within a section

### ISSUE THREAD

**Issue by roryhewitt** [akamai/AkamaiOPEN-edgegrid-node#50] opened 2019-02-14 19:24 UTC
Currently, the Node implementation (maybe others too) _only_ allows 4 lines within each section, e.g.:

```
[default]
client_secret = b4Dh...
host = akab-vos...
access_token = akab-7dt...
client_token = akab-evi...
```

However, I have gotten in the habit of adding additional information as separate values, e.g.:

```
[default]
client_description = Rory Hewitt
open_identity_id = f4y...
api_authorization_0 = Property Manager (PAPI); /papi; READ-WRITE
api_authorization_1 = Identity Management: API; /identity-management/v1/open-identities/*/credentials*; READ-ONLY
api_authorization_2 = Network Lists; /network-list; READ-ONLY
api_authorization_3 = User Admin V2; /identity-management/v*/user-admin/*; READ-ONLY
api_authorization_4 = Firewall Rules Manager; /firewall-rules-manager; READ-ONLY
client_secret = b4Dh...
host = akab-vos...
access_token = akab-7dt...
client_token = akab-evi...
```

That causes problems with Node, since it only reads the first 4 lines, and expects (client_secret, host, access_token and client_token)...

Can we change this to explicitly look for those 4 values within a section, and ignore any other lines?

**Comment by joaquin-gimenez** [comment] 2019-02-19 16:18
@roryhewitt The library does not read the first 4 lines, it looks for 'client_token', 'client_secret', 'access_token' and 'host' from the object (containing all other configurations as well and regardless of any order). It might have been a syntax error on the new lines added. If you can reproduce the issue please attach a screen with the error message. Let me know if this helped. 
Cheers

**Comment by roryhewitt** [comment] 2019-02-19 17:54
Hey @joaquin-gimenez here you go...

![image](https://user-images.githubusercontent.com/11558891/53036053-c1bae580-342b-11e9-80e2-62ecdfc5859f.png)

The first request had my .edgerc file as follows:

```
[image-manager]
client_secret = fOW...
host = akab-2i2...
access_token = akab-lxw...
client_token = akab-c3c...
```

and it worked successfully.

Then, I added a 'client_description' value, tried again, and I got the failure.

```
[image-manager]
client_description = Rory Hewitt
client_secret = fOW...
host = akab-2i2...
access_token = akab-lxw...
client_token = akab-c3c...
```

Finally, I added the comment _after_ the other 4 lines, and it worked again:

```
[image-manager]
client_secret = fOW...
host = akab-2i2...
access_token = akab-lxw...
client_token = akab-c3c...
client_description = Rory Hewitt
```

The fact that it worked when I added the comment after the four 'real' ;lines is what leads me to believe that some where it's only checking the first 4 lines. But obviously I could be wrong :)

**Comment by roryhewitt** [comment] 2019-02-19 17:55
Here are the commands in the screenshot as copy/paste text:

```
ERROR:
         TypeError: Cannot read property 'replace' of null
    at Object.dataToSign (C:\Users\rhewitt\.akamai-cli\src\cli-auth\node_modules\edgegrid\src\helpers.js:72:28)
    at Object.signRequest (C:\Users\rhewitt\.akamai-cli\src\cli-auth\node_modules\edgegrid\src\helpers.js:144:39)
    at makeAuthHeader (C:\Users\rhewitt\.akamai-cli\src\cli-auth\node_modules\edgegrid\src\auth.js:40:58)
    at Object.generateAuth (C:\Users\rhewitt\.akamai-cli\src\cli-auth\node_modules\edgegrid\src\auth.js:65:37)
    at EdgeGrid.auth (C:\Users\rhewitt\.akamai-cli\src\cli-auth\node_modules\edgegrid\src\api.js:60:23)
    at Promise (C:\Users\rhewitt\.akamai-cli\src\cli-auth\src\egauth.js:91:24)
    at new Promise (<anonymous>)
    at edgeGridAuth.verify (C:\Users\rhewitt\.akamai-cli\src\cli-auth\src\egauth.js:86:16)
    at verify (C:\Users\rhewitt\.akamai-cli\src\cli-auth\bin\akamaiAuth:44:14)
    at TypeCommand.run [as _runHandler] (C:\Users\rhewitt\.akamai-cli\src\cli-auth\bin\akamaiAuth:81:20)
```

**Comment by roryhewitt** [comment] 2019-02-19 18:19
OK, I suspect the problem is in *edgerc.js* (part of edgegrid):

```
function validatedConfig(config) {

  if (!(config.host && config.access_token &&
        config.client_secret && config.client_token)) {
          var errorMessage = "";
          var tokens = 
            ['client_token', 'client_secret','access_token','host'];
          tokens.forEach(function(token) {
            if (!config[token]) {
              errorMessage += "\nMissing: " + token;
            }
          })
          console.log('Missing part of the configuration:\n' + errorMessage);
          return {};
        }

  if (config.host.indexOf('https://') > -1) {
    return config;
  }

  config.host = 'https://' + config.host;
      
  return config;
}
```

That `tokens.forEach` will fail, since it's only going to run 4 times (once per token). So if there are any lines which come _before_ any of those tokens, it'll miss them.

**Comment by joaquin-gimenez** [comment] 2019-02-19 18:57
@roryhewitt thanks for the details, i'll have a look

**Comment by synedra** [comment] 2019-02-28 19:40
Joaquin, what's the blocker on this one?

Kirsten

**Comment by joaquin-gimenez** [comment] 2019-02-28 19:49
@synedra this was a bug that was fixed previously, but as cli-auth didn't have the latest edgegrid version, it was not running the fix. I've updated the edgegrid version on cli-auth and with it if you update akamai the issue is fixed
https://github.com/akamai/cli-auth/pull/11

**Comment by piotrpio** [comment] 2021-07-07 07:23
Hello @roryhewitt 
This bug seems to have been fixed for this package in version 3.0.5. Can you confirm whether we can close the issue?

Thanks

**Comment by roryhewitt** [comment] 2021-07-07 17:47
@piotrpio Well the code itself looks basically the same, but on running the package, the problem appears to have resolved itself. Let's go ahead and close it -it can always be reopened if it pops back up :)

**Comment by piotrpio** [comment] 2021-07-09 07:32
Thanks for letting me know, I'm closing the issue then :)

**Closed by piotrpio** 2021-07-09 07:32 UTC
